#ifndef MODEL_CORE_COMPONENTTYPE_H__
#define MODEL_CORE_COMPONENTTYPE_H__

namespace Game {

enum ComponentType
{
  COMPONENT_TYPE_FIRST,
  COMPONENT_TYPE_ANIMATION = COMPONENT_TYPE_FIRST,
  COMPONENT_TYPE_ASPECT,
  COMPONENT_TYPE_BEHAVIOUR,
  COMPONENT_TYPE_COLLISION,
  COMPONENT_TYPE_MOTION,
  COMPONENT_TYPE_PARTICLE,
  COMPONENT_TYPE_PLACEMENT,
  COMPONENT_TYPE_PLACEMENTCONSTRAINT,
  COMPONENT_TYPE_SCORE,
  COMPONENT_TYPE_STEERING,
  COMPONENT_TYPE_LAST       
};

}

#endif // MODEL_CORE_COMPONENTTYPE_H__